In [99]:
from nn import NeuralNetwork
import numpy as np
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split

In [146]:
digits = load_digits()
print(digits.images[15])
print(digits.data[15])
print(digits.target[15])


[[ 0.  5. 12. 13. 16. 16.  2.  0.]
 [ 0. 11. 16. 15.  8.  4.  0.  0.]
 [ 0.  8. 14. 11.  1.  0.  0.  0.]
 [ 0.  8. 16. 16. 14.  0.  0.  0.]
 [ 0.  1.  6.  6. 16.  0.  0.  0.]
 [ 0.  0.  0.  5. 16.  3.  0.  0.]
 [ 0.  1.  5. 15. 13.  0.  0.  0.]
 [ 0.  4. 15. 16.  2.  0.  0.  0.]]
[ 0.  5. 12. 13. 16. 16.  2.  0.  0. 11. 16. 15.  8.  4.  0.  0.  0.  8.
 14. 11.  1.  0.  0.  0.  0.  8. 16. 16. 14.  0.  0.  0.  0.  1.  6.  6.
 16.  0.  0.  0.  0.  0.  0.  5. 16.  3.  0.  0.  0.  1.  5. 15. 13.  0.
  0.  0.  0.  4. 15. 16.  2.  0.  0.  0.]
5


In [143]:
print(dir(digits))

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']


In [129]:
digits = load_digits(return_X_y=True)
data = digits[0]
target = digits[1]
print(target)
#X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.15, random_state=42)

[0 1 2 ... 8 9 8]


In [115]:
lr=.5
seed=1
batch_size=2
epochs=2
nn = NeuralNetwork([{'input_dim': 64, 'output_dim': 16, 'activation': 'sigmoid'},
                    {'input_dim': 16, 'output_dim': 16, 'activation': 'sigmoid'}],
                   lr, seed, batch_size, epochs, 'binary cross entropy')

In [117]:
nn.fit(X_train, y_train, X_test, y_test)

ValueError: shapes (270,16) and (64,16) not aligned: 16 (dim 1) != 64 (dim 0)